### ISSUE TITLE
Should we allow registerRouter() to be called multiple times?

### ISSUE THREAD

**Issue by yoshisatoyanagisawa** [WICG/service-worker-static-routing-api#10]
The issue was originally asked by @sisidovski in https://github.com/w3c/ServiceWorker/issues/1373#issuecomment-1667123029.

To allow 3rd parties use registerRouter() to handle something, allowing registerRouter to be called multiple times was suggested.
In the discussion in https://github.com/w3c/ServiceWorker/issues/1373, people are roughly agreed on allowing to call the registration function multiple times.  However, renaming the function name was suggested there.

**Comment by domenic** [comment]
I think `registerRoutes()` is a reasonable rename. In https://github.com/w3c/ServiceWorker/issues/1373#issuecomment-1671123834 @jakearchibald seems to slightly prefer `addRoutes()`. Either seem good to me.

**Comment by yoshisatoyanagisawa** [comment]
Now `registerRouter()` has been renamed, and can be called for multiple times.
