### ISSUE TITLE
Service worker throwing "addRoutes is not a function" error

### ISSUE THREAD

**Issue by shubham9560** [WICG/service-worker-static-routing-api#16]
I have signed up for Origin-trial for Static routing API. But somehow it is not working for me when I send origin-trial token in response header of Service-worker request. But it works without this token when I enable the StaticRoutingAPI flag in chrome canary. Is this a bug or I am missing anything here?

**Comment by yoshisatoyanagisawa** [comment]
Sorry for the slow reply, and thank you for signing up for the origin trial.
Let me clarify the current situation.
You are currently using the latest Chrome canary, right?
When you make your server send the origin trial token to the Chrome canary, it does not understand `addRoutes()`.
However, when you manually enables `#service-worker-static-router` with the Chrome canary, it understand `addRoutes()`.
Then, it sounds like the path with the origin trial token has some issues.  Note that without the origin trial token or the flag, Chrome does not have `addRoutes()` in `InstallEvent`.  i.e. throwing "addRoutes is not a function" suggest lack of either of them.

Unfortunately, from what you wrote here, I can hardly guess what you actually did for the origin trial.  Let me ask from simple questions.
- What is the Chrome canary version you use for testing?
- When you create an origin trial token, you are sure to choose "[ServiceWorker static routing API](https://developer.chrome.com/origintrials/#/view_trial/1458040379361198081)", right?
- When you create a token, you are sure to specify the [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin) you are going to run the origin trial, right?
- When you open devtools and connect to the site, do you see that the Origin-Trial header is sent in the response?
   Note that you **cannot** use an HTML meta tag for setting the token.  It can only be used as an HTTP header.
- Is that matches with the token you got from the origin trial registration page?
- Do you see the Origin-Trial header in every resource sent from the site?

**Comment by shubham9560** [comment]
Hi,

Please find my answers below:

1. **What is the Chrome canary version you use for testing?**
Version 122.0.6174.0 
2. **When you create an origin trial token, you are sure to choose "[ServiceWorker static routing API](https://developer.chrome.com/origintrials/#/view_trial/1458040379361198081)", right?**
Yes
3. **When you create a token, you are sure to specify the [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin) you are going to run the origin trial, right?**
Yes
4. **When you open devtools and connect to the site, do you see that the Origin-Trial header is sent in the response?Note that you cannot use an HTML meta tag for setting the token. It can only be used as an HTTP header.**
Yes
5. **Is that matches with the token you got from the origin trial registration page?**
Yes
6. **Do you see the Origin-Trial header in every resource sent from the site?**
No

**Comment by yoshisatoyanagisawa** [comment]
Sorry for the slow reply, the approach sounds valid to me, but I suppose there is something missing.
Is it possible for me to take a look at your site?  Or, is it possible to show some essence of your attempts with the site like glitch.me?

Just FYI, but we have a demo on the static routing API in https://sw-static-routing-demo.glitch.me/.  I hope following the approach there helps.

**Comment by yoshisatoyanagisawa** [comment]
Just FYI, but the API will be available with Chrome 123.  Please see the following blog post:
https://developer.chrome.com/blog/chrome-123-beta?hl=en#service_worker_static_routing_api

You do not need the origin trial token if you use the latest beta.

**Comment by yoshisatoyanagisawa** [comment]
Chrome 123 has been released.  It means that `addRoutes()` is usable with the latest Chrome.
Therefore, I am going to close this issue.

Please feel free to reopen if you continue seeing the error with the latest Chrome.
