### ISSUE TITLE
Certain URLPatterns don't work; missing 'not' condition

### ISSUE THREAD

**Issue by screenspan** [WICG/service-worker-static-routing-api#21]
# SHORT DESCRIPTION
We'd like to be able to 
* a) bypass the Service Worker for multiple URL patterns; or 
* b) use the Service Worker to fetch all URLs except certain URL patterns

# CURRENT BEHAVIOR
Google Version 123.0.6289.0 (Developer Build) (arm64) on Mac OS 14.3.1
Date: 2024-02-16

The URL Pattern API does allow for alternates using `|`, e.g.
![image](https://github.com/WICG/service-worker-static-routing-api/assets/19509110/129fb0b4-132f-4113-9f73-c2bfcb9b3345)

But using alternates doesn't currently work in the Service Worker Static Routing API. The following code results in an error:

```js
self.addEventListener('install', event => {
  if (event.addRoutes) {
    event.addRoutes([
      {
        condition: {
          urlPattern: new URLPattern({ pathname: "/(collections|search|621532|account|pages|cart|checkout)/*" })
        },
        source: "network"
      },
    ]);
  }
});
```
![image](https://github.com/WICG/service-worker-static-routing-api/assets/19509110/c469732b-9dc5-430f-9cd0-9d27ba88ead8)

We therefore have to resort to a verbose way of declaring multiple patterns that does let us bypass the Service Worker:

```js
self.addEventListener('install', event => {
  if (event.addRoutes) {
    event.addRoutes([
      {
        condition: {
          urlPattern: new URLPattern({pathname: "/collections*"})
        },
        source: "network"
      },

      {
        condition: {
          urlPattern: new URLPattern({pathname: "/search*"})
        },
        source: "network"
      },
      {
        condition: {
          urlPattern: new URLPattern({pathname: "/621532*"})
        },
        source: "network"
      },
      {
        condition: {
          urlPattern: new URLPattern({pathname: "/account*"})
        },
        source: "network"
      },
      {
        condition: {
          urlPattern: new URLPattern({pathname: "/pages*"})
        },
        source: "network"
      },
      {
        condition: {
          urlPattern: new URLPattern({pathname: "/cart*"})
        },
        source: "network"
      },
      {
        condition: {
          urlPattern: new URLPattern({pathname: "/checkouts*"})
        },
        source: "network"
      },
      {
        condition: {
          urlPattern: new URLPattern({pathname: "/"})
        },
        source: "network"
      }]);
  }
});
```

Result: A matched URL is fetched from the network as per Service Worker Static Routing API.
![image](https://github.com/WICG/service-worker-static-routing-api/assets/19509110/b39750f2-0731-4f58-8b64-b401e3b30c15)

# DESIRED BEHAVIOR
## Pattern alternatives
Use pattern alternatives separated by a pipe character, e.g.

```js
self.addEventListener('install', event => {
  if (event.addRoutes) {
    event.addRoutes([
      {
        condition: {
          urlPattern: new URLPattern({ pathname: "/(collections|search|621532|account|pages|cart|checkout)/*" })
        },
        source: "network"
      },
    ]);
  }
});
```

## Exclude URL patterns using 'not' condition
Add all routes _except_ for certain patterns by using a `not` condition, as the [URL Pattern API](https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API#custom_regular_expression_groups) apparently doesn't have a way to exclude patterns.

```js
self.addEventListener('install', event => {
  if (event.addRoutes) {
    event.addRoutes([
      {
        condition: {
          not: [{ // This would be helpful!
            urlPattern: new URLPattern({ pathname: "/(collections|search|621532|account|pages|cart|checkout)/*" })
          }]
        },
        source: "fetch-event"
      },
    ]);
  }
});
```

## Show 'Source' in Network Panel
Currently routed via Service Worker Static Routing API are annotated by `(ServiceWorker router)` in the Network panel.
![image](https://github.com/WICG/service-worker-static-routing-api/assets/19509110/f26ed809-c6fd-44a1-984e-e4f85077d26b)

Ideally, the source would also be displayed, e.g.
`(ServiceWorker: routed to network)`

**Comment by sisidovski** [comment]
Thank you @screenspan for reporting this!

Currently the API intentionally prohibits the URLPattern input with having regular expressions because from security concerns. Although it's not merged yet, we have a mention in the proposed spec.
https://github.com/w3c/ServiceWorker/pull/1701/files#diff-7bdebf23eab87aaf2676a41586076394031b6b98fde24e35d1672aa65a1cc0feR3373-R3375

You can check if your URLPattern input has a regexp or not, by using [hasRegExpGroups](https://urlpattern.spec.whatwg.org/#dom-urlpattern-hasregexpgroups).

```
new URLPattern({pathname: '/(collections|search|621532|account|pages|cart|checkout)/*'}).hasRegExpGroups
=> true
```

> We therefore have to resort to a verbose way of declaring multiple patterns that does let us bypass the Service Worker:

Agree, that's not a smart solution, but currently having multiple patterns is the right approach.

> Show 'Source' in Network Panel

I understand this is important for the debug, but this is more like a chrome DevTools feature. If possible, could you file a bug to https://crbug.com/ ?

**Comment by yoshisatoyanagisawa** [comment]
Thank you for the report,

As @sisidovski mentioned, using regexp is intentionally prohibited.  `hasRegExpGroups` has been introduced for checking that.

For the pattern you wrote, I suppose you can also use the `or` condition.

```
self.addEventListener('install', event => {
  if (event.addRoutes) {
    event.addRoutes([
      {
        condition: {
          or: [
            {urlPattern: new URLPattern({pathname: "/collections*"})},
            {urlPattern: new URLPattern({pathname: "/search*"})},
            {urlPattern: new URLPattern({pathname: "/621532*"})},
            {urlPattern: new URLPattern({pathname: "/account*"})},
            {urlPattern: new URLPattern({pathname: "/pages*"})},
            {urlPattern: new URLPattern({pathname: "/cart*"})},
            {urlPattern: new URLPattern({pathname: "/checkouts*"})},
            {urlPattern: new URLPattern({pathname: "/"})}
         ]
        },
        source: "network"
      }]);
  }
});
```

Unfortunately, Chromium only implements the `or` condition, and other conjunctive conditions are not implemented yet.

When you hover the network panel entry, router ID will be shown.  You can find an associated source by checking the ID in the routes section shown in the Application panel.  However, I understand it is not so convenient.

As @sisidovski mentioned, please feel free to file a crbug.

**Comment by screenspan** [comment]
Hi @sisidovski and @yoshisatoyanagisawa , thanks for the additional information. 

Using the `or` condition, as @yoshisatoyanagisawa suggested, did work for me. 

If I understand the [proposal for the final form](https://github.com/WICG/service-worker-static-routing-api/blob/main/final-form.md) of the API, a `not` condition will be added:

```
dictionary RouterNotCondition : RouterCondition {
  RouterCondition not;
};
```

I think that'll be helpful once implemented.

Are there any other restrictions on using the URL Pattern API with Static Routing besides custom RegExp groups?

I've [filed a crbug](https://issues.chromium.org/u/2/issues/325838098) for the DevTools feature request, so feel free to close this issue if you want.

**Comment by yoshisatoyanagisawa** [comment]
> Are there any other restrictions on using the URL Pattern API with Static Routing besides custom RegExp groups?

Except for prohibiting use of a regular expression (or, what URLPattern think as a regular expression), there should not be any restrictions.

One think you may need an attention to use URLPattern is that an implicit base URL configuration for short-hands.  However, since you use the URLPattern object, you should not be affected.
It is discussed in https://github.com/whatwg/urlpattern/issues/182, and the static routing API follows:
https://urlpattern.spec.whatwg.org/#other-specs-javascript

I do not come up with anything else.

**Comment by yoshisatoyanagisawa** [comment]
FYI, the "not" condition implementation is tracked in https://issues.chromium.org/issues/328565554.

**Comment by yoshisatoyanagisawa** [comment]
Note that the not condition has been implemented behind the flag (ServiceWorkerStaticRouterNotConditionEnabled).

**Comment by yoshisatoyanagisawa** [comment]
FYI, I2S has been sent. https://groups.google.com/a/chromium.org/g/blink-dev/c/1HxS284iKCE

**Comment by yoshisatoyanagisawa** [comment]
Let me mark this resolved.
- a regular expression pattern is not supported in ServiceWorker static routing API because the pattern is executed in the browser process, and there is a security concern to support executing arbitrary regular expressions there.
- the "not" condition has been available since M127.
