### ISSUE TITLE
How an empty condition in the "not" condition should be handled?

### ISSUE THREAD

**Issue by yoshisatoyanagisawa** [WICG/service-worker-static-routing-api#22]
If "not" condition gets an empty condition, i.e. {}, how should it be handled?
I suppose options are:
1. raise.
2. treat it as always true.

We used to [treat](https://github.com/WICG/service-worker-static-routing-api/issues/9) an empty list to "or" condition as always false.  However, I suppose it fine to raise.
What do others think?

**Comment by yoshisatoyanagisawa** [comment]
@domenic @azaika I guess you have opinions in this area.

**Comment by azaika** [comment]
IMO, raising is the good option.
The "or" condition allows empty lists because they are naturally considered logical identity, and this does not fits to the "not".

**Comment by domenic** [comment]
I agree with @azaika

**Comment by yoshisatoyanagisawa** [comment]
Thank you for sharing your opinions, both.  Raising sounds the way to go.
However, to gather opinions from others, let me leave the github issue open for several weeks before making the final decision.

**Comment by yoshisatoyanagisawa** [comment]
Drafted the PR in https://github.com/w3c/ServiceWorker/pull/1711

**Comment by yoshisatoyanagisawa** [comment]
Two weeks have passed.  It might be fine to close this.
No contents in the "not" condition is error.

**Comment by yoshisatoyanagisawa** [comment]
Please feel free to leave comments in the spec PR by the way.
