### ISSUE TITLE
Renaming attributes on Conditional Syntax

### ISSUE THREAD

**Issue by azaika** [WICG/service-worker-static-routing-api#8]
The proposed Conditional Syntax ("or", "and", "not") [[Design Doc]](https://docs.google.com/document/d/1B2D8w_2M4j9CZC1VccBOAhfCdiRP3yPCSV5UKKDhU70) are all C++ keywords, and thus may prevent browsers from implementing this proposal.
In fact, WebIDL binding tools for C++ in Chromium emit errors when I try to use the name "or".

Therefore, I suggest changing these names not to conflict with the C++ keywords.
I think "any" and "all" are good alternatives.

**Comment by chikamune-cr** [comment]
The other possible alternatives of "and" and "or" could be "every" and "some" to be consistent with Array's every() and some(). The alternative of "not" could be "invert".

**Comment by bathos** [comment]
> In fact, WebIDL binding tools for C++ in Chromium emit errors when I try to use the name "or".

It’s a unique terminal symbol in Web IDL, a keyword in union type syntax. The _identifier_ with the string value “or” is written `_or` in Web IDL, with a leading underscore. It’s not related to C++.

**Comment by azaika** [comment]
@bathos Thank you for your kind comments. You are right: my concern was ephemeral.

I wrongly thought the conflict was unavoidable just because using only the leading underscore (`_or`) didn't work for me. However, I found that WebIDL's [ImplmentedAs](https://www.chromium.org/developers/web-idl-interfaces/#c) property, which was used to implement the `continue` feature you mentioned, solves the problem.
